apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-pig-backend
  namespace: smart-pig-defi
  labels:
    app: smart-pig-backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-pig-backend
  template:
    metadata:
      labels:
        app: smart-pig-backend
        tier: backend
    spec:
      imagePullSecrets:
        - name: smart-pig-registry-secret
      containers:
        - name: backend
          image: ghcr.io/caroltea/smart-pig-defi-backend:IMAGE_TAG
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: smart-pig-config
            - secretRef:
                name: smart-pig-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      securityContext:
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - smart-pig-backend
                topologyKey: kubernetes.io/hostname

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-pig-backend-pdb
  namespace: smart-pig-defi
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-pig-backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-pig-backend-hpa
  namespace: smart-pig-defi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-pig-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80