apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-pig-docs
  namespace: smart-pig-defi
  labels:
    app: smart-pig-docs
    component: documentation
    part-of: smart-pig-defi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: smart-pig-docs
  template:
    metadata:
      labels:
        app: smart-pig-docs
        component: documentation
        part-of: smart-pig-defi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/health"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: docs
        image: ghcr.io/carolTea/smart-pig-defi-docs:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: smart-pig-config
              key: app-version
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-cache
          mountPath: /var/cache/nginx
        - name: var-log
          mountPath: /var/log/nginx
        - name: var-run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-cache
        emptyDir: {}
      - name: var-log
        emptyDir: {}
      - name: var-run
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: smart-pig-docs-service
  namespace: smart-pig-defi
  labels:
    app: smart-pig-docs
    component: documentation
    part-of: smart-pig-defi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: smart-pig-docs
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-pig-docs-pdb
  namespace: smart-pig-defi
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-pig-docs
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-pig-docs-hpa
  namespace: smart-pig-defi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-pig-docs
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60